## STATIC CONFIGURATION
log:
  level: INFO
accessLog:
  filePath: "./access.log"

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

